// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.6.1
// source: frame1.proto

package frameproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner_Position int32

const (
	Banner_TOP    Banner_Position = 0
	Banner_CENTER Banner_Position = 1
)

// Enum value maps for Banner_Position.
var (
	Banner_Position_name = map[int32]string{
		0: "TOP",
		1: "CENTER",
	}
	Banner_Position_value = map[string]int32{
		"TOP":    0,
		"CENTER": 1,
	}
)

func (x Banner_Position) Enum() *Banner_Position {
	p := new(Banner_Position)
	*p = x
	return p
}

func (x Banner_Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Banner_Position) Descriptor() protoreflect.EnumDescriptor {
	return file_frame1_proto_enumTypes[0].Descriptor()
}

func (Banner_Position) Type() protoreflect.EnumType {
	return &file_frame1_proto_enumTypes[0]
}

func (x Banner_Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Banner_Position.Descriptor instead.
func (Banner_Position) EnumDescriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{4, 0}
}

type Vec3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Mat3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row1 *Vec3 `protobuf:"bytes,1,opt,name=row1,proto3" json:"row1,omitempty"`
	Row2 *Vec3 `protobuf:"bytes,2,opt,name=row2,proto3" json:"row2,omitempty"`
	Row3 *Vec3 `protobuf:"bytes,3,opt,name=row3,proto3" json:"row3,omitempty"`
}

func (x *Mat3) Reset() {
	*x = Mat3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mat3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mat3) ProtoMessage() {}

func (x *Mat3) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mat3.ProtoReflect.Descriptor instead.
func (*Mat3) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{1}
}

func (x *Mat3) GetRow1() *Vec3 {
	if x != nil {
		return x.Row1
	}
	return nil
}

func (x *Mat3) GetRow2() *Vec3 {
	if x != nil {
		return x.Row2
	}
	return nil
}

func (x *Mat3) GetRow3() *Vec3 {
	if x != nil {
		return x.Row3
	}
	return nil
}

type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarPosition *Vec3   `protobuf:"bytes,1,opt,name=avatarPosition,proto3" json:"avatarPosition,omitempty"`
	AvatarToVec    *Vec3   `protobuf:"bytes,6,opt,name=avatarToVec,proto3" json:"avatarToVec,omitempty"`
	AvatarUpVec    *Vec3   `protobuf:"bytes,7,opt,name=avatarUpVec,proto3" json:"avatarUpVec,omitempty"`
	AnimationPhase float64 `protobuf:"fixed64,3,opt,name=animationPhase,proto3" json:"animationPhase,omitempty"`
	CameraPosition *Vec3   `protobuf:"bytes,4,opt,name=cameraPosition,proto3" json:"cameraPosition,omitempty"`
	CameraToVec    *Vec3   `protobuf:"bytes,8,opt,name=cameraToVec,proto3" json:"cameraToVec,omitempty"`
	CameraUpVec    *Vec3   `protobuf:"bytes,9,opt,name=cameraUpVec,proto3" json:"cameraUpVec,omitempty"`
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{2}
}

func (x *Avatar) GetAvatarPosition() *Vec3 {
	if x != nil {
		return x.AvatarPosition
	}
	return nil
}

func (x *Avatar) GetAvatarToVec() *Vec3 {
	if x != nil {
		return x.AvatarToVec
	}
	return nil
}

func (x *Avatar) GetAvatarUpVec() *Vec3 {
	if x != nil {
		return x.AvatarUpVec
	}
	return nil
}

func (x *Avatar) GetAnimationPhase() float64 {
	if x != nil {
		return x.AnimationPhase
	}
	return 0
}

func (x *Avatar) GetCameraPosition() *Vec3 {
	if x != nil {
		return x.CameraPosition
	}
	return nil
}

func (x *Avatar) GetCameraToVec() *Vec3 {
	if x != nil {
		return x.CameraToVec
	}
	return nil
}

func (x *Avatar) GetCameraUpVec() *Vec3 {
	if x != nil {
		return x.CameraUpVec
	}
	return nil
}

type Menu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries          []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	ActiveEntryIndex uint32   `protobuf:"varint,2,opt,name=activeEntryIndex,proto3" json:"activeEntryIndex,omitempty"`
}

func (x *Menu) Reset() {
	*x = Menu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{3}
}

func (x *Menu) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Menu) GetActiveEntryIndex() uint32 {
	if x != nil {
		return x.ActiveEntryIndex
	}
	return 0
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines    []string        `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Position Banner_Position `protobuf:"varint,2,opt,name=position,proto3,enum=ghostpacer.frame.Banner_Position" json:"position,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{4}
}

func (x *Banner) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Banner) GetPosition() Banner_Position {
	if x != nil {
		return x.Position
	}
	return Banner_TOP
}

type Legend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpActive     bool `protobuf:"varint,1,opt,name=upActive,proto3" json:"upActive,omitempty"`
	SelectActive bool `protobuf:"varint,2,opt,name=selectActive,proto3" json:"selectActive,omitempty"`
	DownActive   bool `protobuf:"varint,3,opt,name=downActive,proto3" json:"downActive,omitempty"`
}

func (x *Legend) Reset() {
	*x = Legend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Legend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Legend) ProtoMessage() {}

func (x *Legend) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Legend.ProtoReflect.Descriptor instead.
func (*Legend) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{5}
}

func (x *Legend) GetUpActive() bool {
	if x != nil {
		return x.UpActive
	}
	return false
}

func (x *Legend) GetSelectActive() bool {
	if x != nil {
		return x.SelectActive
	}
	return false
}

func (x *Legend) GetDownActive() bool {
	if x != nil {
		return x.DownActive
	}
	return false
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar *Avatar `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Legend *Legend `protobuf:"bytes,2,opt,name=legend,proto3" json:"legend,omitempty"`
	Menu   *Menu   `protobuf:"bytes,3,opt,name=menu,proto3" json:"menu,omitempty"`
	Banner *Banner `protobuf:"bytes,4,opt,name=banner,proto3" json:"banner,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frame1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frame1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frame1_proto_rawDescGZIP(), []int{6}
}

func (x *Frame) GetAvatar() *Avatar {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *Frame) GetLegend() *Legend {
	if x != nil {
		return x.Legend
	}
	return nil
}

func (x *Frame) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *Frame) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

var File_frame1_proto protoreflect.FileDescriptor

var file_frame1_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x22, 0x30, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x7a, 0x22, 0x8a, 0x01, 0x0a, 0x04, 0x4d, 0x61, 0x74, 0x33, 0x12, 0x2a, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63,
	0x33, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x31, 0x12, 0x2a, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63,
	0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x04, 0x72,
	0x6f, 0x77, 0x32, 0x12, 0x2a, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x33, 0x22,
	0xa4, 0x03, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x3e, 0x0a, 0x0e, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x54, 0x6f, 0x56, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54,
	0x6f, 0x56, 0x65, 0x63, 0x12, 0x38, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70,
	0x56, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63,
	0x33, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x56, 0x65, 0x63, 0x12, 0x26,
	0x0a, 0x0e, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0e, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x54, 0x6f, 0x56, 0x65, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68,
	0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56,
	0x65, 0x63, 0x33, 0x52, 0x0b, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x54, 0x6f, 0x56, 0x65, 0x63,
	0x12, 0x38, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x55, 0x70, 0x56, 0x65, 0x63, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63,
	0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0b, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x55, 0x70, 0x56, 0x65, 0x63, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03,
	0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x22, 0x4c, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x10, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x7e, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61,
	0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x07, 0x0a, 0x03, 0x54, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x45, 0x4e, 0x54,
	0x45, 0x52, 0x10, 0x01, 0x22, 0x68, 0x0a, 0x06, 0x4c, 0x65, 0x67, 0x65, 0x6e, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0xc9,
	0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x6c, 0x65,
	0x67, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x4c, 0x65,
	0x67, 0x65, 0x6e, 0x64, 0x52, 0x06, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x04,
	0x6d, 0x65, 0x6e, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x12, 0x30, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x50,
	0x61, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x67,
	0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2f,
	0x67, 0x6f, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frame1_proto_rawDescOnce sync.Once
	file_frame1_proto_rawDescData = file_frame1_proto_rawDesc
)

func file_frame1_proto_rawDescGZIP() []byte {
	file_frame1_proto_rawDescOnce.Do(func() {
		file_frame1_proto_rawDescData = protoimpl.X.CompressGZIP(file_frame1_proto_rawDescData)
	})
	return file_frame1_proto_rawDescData
}

var file_frame1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frame1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_frame1_proto_goTypes = []interface{}{
	(Banner_Position)(0), // 0: ghostpacer.frame.Banner.Position
	(*Vec3)(nil),         // 1: ghostpacer.frame.Vec3
	(*Mat3)(nil),         // 2: ghostpacer.frame.Mat3
	(*Avatar)(nil),       // 3: ghostpacer.frame.Avatar
	(*Menu)(nil),         // 4: ghostpacer.frame.Menu
	(*Banner)(nil),       // 5: ghostpacer.frame.Banner
	(*Legend)(nil),       // 6: ghostpacer.frame.Legend
	(*Frame)(nil),        // 7: ghostpacer.frame.Frame
}
var file_frame1_proto_depIdxs = []int32{
	1,  // 0: ghostpacer.frame.Mat3.row1:type_name -> ghostpacer.frame.Vec3
	1,  // 1: ghostpacer.frame.Mat3.row2:type_name -> ghostpacer.frame.Vec3
	1,  // 2: ghostpacer.frame.Mat3.row3:type_name -> ghostpacer.frame.Vec3
	1,  // 3: ghostpacer.frame.Avatar.avatarPosition:type_name -> ghostpacer.frame.Vec3
	1,  // 4: ghostpacer.frame.Avatar.avatarToVec:type_name -> ghostpacer.frame.Vec3
	1,  // 5: ghostpacer.frame.Avatar.avatarUpVec:type_name -> ghostpacer.frame.Vec3
	1,  // 6: ghostpacer.frame.Avatar.cameraPosition:type_name -> ghostpacer.frame.Vec3
	1,  // 7: ghostpacer.frame.Avatar.cameraToVec:type_name -> ghostpacer.frame.Vec3
	1,  // 8: ghostpacer.frame.Avatar.cameraUpVec:type_name -> ghostpacer.frame.Vec3
	0,  // 9: ghostpacer.frame.Banner.position:type_name -> ghostpacer.frame.Banner.Position
	3,  // 10: ghostpacer.frame.Frame.avatar:type_name -> ghostpacer.frame.Avatar
	6,  // 11: ghostpacer.frame.Frame.legend:type_name -> ghostpacer.frame.Legend
	4,  // 12: ghostpacer.frame.Frame.menu:type_name -> ghostpacer.frame.Menu
	5,  // 13: ghostpacer.frame.Frame.banner:type_name -> ghostpacer.frame.Banner
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_frame1_proto_init() }
func file_frame1_proto_init() {
	if File_frame1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frame1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mat3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Menu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Legend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frame1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frame1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame1_proto_goTypes,
		DependencyIndexes: file_frame1_proto_depIdxs,
		EnumInfos:         file_frame1_proto_enumTypes,
		MessageInfos:      file_frame1_proto_msgTypes,
	}.Build()
	File_frame1_proto = out.File
	file_frame1_proto_rawDesc = nil
	file_frame1_proto_goTypes = nil
	file_frame1_proto_depIdxs = nil
}
