// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frame1.proto

package frameproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Banner_Position int32

const (
	Banner_TOP    Banner_Position = 0
	Banner_CENTER Banner_Position = 1
)

var Banner_Position_name = map[int32]string{
	0: "TOP",
	1: "CENTER",
}

var Banner_Position_value = map[string]int32{
	"TOP":    0,
	"CENTER": 1,
}

func (x Banner_Position) String() string {
	return proto.EnumName(Banner_Position_name, int32(x))
}

func (Banner_Position) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{4, 0}
}

type Vec3 struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec3) Reset()         { *m = Vec3{} }
func (m *Vec3) String() string { return proto.CompactTextString(m) }
func (*Vec3) ProtoMessage()    {}
func (*Vec3) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{0}
}

func (m *Vec3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec3.Unmarshal(m, b)
}
func (m *Vec3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec3.Marshal(b, m, deterministic)
}
func (m *Vec3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec3.Merge(m, src)
}
func (m *Vec3) XXX_Size() int {
	return xxx_messageInfo_Vec3.Size(m)
}
func (m *Vec3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec3.DiscardUnknown(m)
}

var xxx_messageInfo_Vec3 proto.InternalMessageInfo

func (m *Vec3) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vec3) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vec3) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Mat3 struct {
	Row1                 *Vec3    `protobuf:"bytes,1,opt,name=row1,proto3" json:"row1,omitempty"`
	Row2                 *Vec3    `protobuf:"bytes,2,opt,name=row2,proto3" json:"row2,omitempty"`
	Row3                 *Vec3    `protobuf:"bytes,3,opt,name=row3,proto3" json:"row3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mat3) Reset()         { *m = Mat3{} }
func (m *Mat3) String() string { return proto.CompactTextString(m) }
func (*Mat3) ProtoMessage()    {}
func (*Mat3) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{1}
}

func (m *Mat3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mat3.Unmarshal(m, b)
}
func (m *Mat3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mat3.Marshal(b, m, deterministic)
}
func (m *Mat3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mat3.Merge(m, src)
}
func (m *Mat3) XXX_Size() int {
	return xxx_messageInfo_Mat3.Size(m)
}
func (m *Mat3) XXX_DiscardUnknown() {
	xxx_messageInfo_Mat3.DiscardUnknown(m)
}

var xxx_messageInfo_Mat3 proto.InternalMessageInfo

func (m *Mat3) GetRow1() *Vec3 {
	if m != nil {
		return m.Row1
	}
	return nil
}

func (m *Mat3) GetRow2() *Vec3 {
	if m != nil {
		return m.Row2
	}
	return nil
}

func (m *Mat3) GetRow3() *Vec3 {
	if m != nil {
		return m.Row3
	}
	return nil
}

type Avatar struct {
	AvatarPosition *Vec3   `protobuf:"bytes,1,opt,name=avatarPosition,proto3" json:"avatarPosition,omitempty"`
	AvatarToVec    *Vec3   `protobuf:"bytes,6,opt,name=avatarToVec,proto3" json:"avatarToVec,omitempty"`
	AvatarUpVec    *Vec3   `protobuf:"bytes,7,opt,name=avatarUpVec,proto3" json:"avatarUpVec,omitempty"`
	AnimationPhase float64 `protobuf:"fixed64,3,opt,name=animationPhase,proto3" json:"animationPhase,omitempty"`
	// Camera vectors should not be included in final protobuf
	CameraPosition       *Vec3    `protobuf:"bytes,4,opt,name=cameraPosition,proto3" json:"cameraPosition,omitempty"`
	CameraToVec          *Vec3    `protobuf:"bytes,8,opt,name=cameraToVec,proto3" json:"cameraToVec,omitempty"`
	CameraUpVec          *Vec3    `protobuf:"bytes,9,opt,name=cameraUpVec,proto3" json:"cameraUpVec,omitempty"`
	ModelIndex           uint32   `protobuf:"varint,10,opt,name=modelIndex,proto3" json:"modelIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Avatar) Reset()         { *m = Avatar{} }
func (m *Avatar) String() string { return proto.CompactTextString(m) }
func (*Avatar) ProtoMessage()    {}
func (*Avatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{2}
}

func (m *Avatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Avatar.Unmarshal(m, b)
}
func (m *Avatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Avatar.Marshal(b, m, deterministic)
}
func (m *Avatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Avatar.Merge(m, src)
}
func (m *Avatar) XXX_Size() int {
	return xxx_messageInfo_Avatar.Size(m)
}
func (m *Avatar) XXX_DiscardUnknown() {
	xxx_messageInfo_Avatar.DiscardUnknown(m)
}

var xxx_messageInfo_Avatar proto.InternalMessageInfo

func (m *Avatar) GetAvatarPosition() *Vec3 {
	if m != nil {
		return m.AvatarPosition
	}
	return nil
}

func (m *Avatar) GetAvatarToVec() *Vec3 {
	if m != nil {
		return m.AvatarToVec
	}
	return nil
}

func (m *Avatar) GetAvatarUpVec() *Vec3 {
	if m != nil {
		return m.AvatarUpVec
	}
	return nil
}

func (m *Avatar) GetAnimationPhase() float64 {
	if m != nil {
		return m.AnimationPhase
	}
	return 0
}

func (m *Avatar) GetCameraPosition() *Vec3 {
	if m != nil {
		return m.CameraPosition
	}
	return nil
}

func (m *Avatar) GetCameraToVec() *Vec3 {
	if m != nil {
		return m.CameraToVec
	}
	return nil
}

func (m *Avatar) GetCameraUpVec() *Vec3 {
	if m != nil {
		return m.CameraUpVec
	}
	return nil
}

func (m *Avatar) GetModelIndex() uint32 {
	if m != nil {
		return m.ModelIndex
	}
	return 0
}

type Menu struct {
	Entries              []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	ActiveEntryIndex     uint32   `protobuf:"varint,2,opt,name=activeEntryIndex,proto3" json:"activeEntryIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{3}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Menu) GetActiveEntryIndex() uint32 {
	if m != nil {
		return m.ActiveEntryIndex
	}
	return 0
}

type Banner struct {
	Lines                []string        `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Position             Banner_Position `protobuf:"varint,2,opt,name=position,proto3,enum=ghostpacer.frame.Banner_Position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{4}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Banner) GetPosition() Banner_Position {
	if m != nil {
		return m.Position
	}
	return Banner_TOP
}

type Legend struct {
	UpActive             bool     `protobuf:"varint,1,opt,name=upActive,proto3" json:"upActive,omitempty"`
	SelectActive         bool     `protobuf:"varint,2,opt,name=selectActive,proto3" json:"selectActive,omitempty"`
	DownActive           bool     `protobuf:"varint,3,opt,name=downActive,proto3" json:"downActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Legend) Reset()         { *m = Legend{} }
func (m *Legend) String() string { return proto.CompactTextString(m) }
func (*Legend) ProtoMessage()    {}
func (*Legend) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{5}
}

func (m *Legend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Legend.Unmarshal(m, b)
}
func (m *Legend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Legend.Marshal(b, m, deterministic)
}
func (m *Legend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Legend.Merge(m, src)
}
func (m *Legend) XXX_Size() int {
	return xxx_messageInfo_Legend.Size(m)
}
func (m *Legend) XXX_DiscardUnknown() {
	xxx_messageInfo_Legend.DiscardUnknown(m)
}

var xxx_messageInfo_Legend proto.InternalMessageInfo

func (m *Legend) GetUpActive() bool {
	if m != nil {
		return m.UpActive
	}
	return false
}

func (m *Legend) GetSelectActive() bool {
	if m != nil {
		return m.SelectActive
	}
	return false
}

func (m *Legend) GetDownActive() bool {
	if m != nil {
		return m.DownActive
	}
	return false
}

type Frame struct {
	Avatar1              *Avatar  `protobuf:"bytes,1,opt,name=avatar1,proto3" json:"avatar1,omitempty"`
	Avatar2              *Avatar  `protobuf:"bytes,2,opt,name=avatar2,proto3" json:"avatar2,omitempty"`
	Legend               *Legend  `protobuf:"bytes,3,opt,name=legend,proto3" json:"legend,omitempty"`
	Menu                 *Menu    `protobuf:"bytes,4,opt,name=menu,proto3" json:"menu,omitempty"`
	Banner               *Banner  `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	CameraPosition       *Vec3    `protobuf:"bytes,6,opt,name=cameraPosition,proto3" json:"cameraPosition,omitempty"`
	CameraToVec          *Vec3    `protobuf:"bytes,7,opt,name=cameraToVec,proto3" json:"cameraToVec,omitempty"`
	CameraUpVec          *Vec3    `protobuf:"bytes,8,opt,name=cameraUpVec,proto3" json:"cameraUpVec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac775132823699ce, []int{6}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetAvatar1() *Avatar {
	if m != nil {
		return m.Avatar1
	}
	return nil
}

func (m *Frame) GetAvatar2() *Avatar {
	if m != nil {
		return m.Avatar2
	}
	return nil
}

func (m *Frame) GetLegend() *Legend {
	if m != nil {
		return m.Legend
	}
	return nil
}

func (m *Frame) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

func (m *Frame) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *Frame) GetCameraPosition() *Vec3 {
	if m != nil {
		return m.CameraPosition
	}
	return nil
}

func (m *Frame) GetCameraToVec() *Vec3 {
	if m != nil {
		return m.CameraToVec
	}
	return nil
}

func (m *Frame) GetCameraUpVec() *Vec3 {
	if m != nil {
		return m.CameraUpVec
	}
	return nil
}

func init() {
	proto.RegisterEnum("ghostpacer.frame.Banner_Position", Banner_Position_name, Banner_Position_value)
	proto.RegisterType((*Vec3)(nil), "ghostpacer.frame.Vec3")
	proto.RegisterType((*Mat3)(nil), "ghostpacer.frame.Mat3")
	proto.RegisterType((*Avatar)(nil), "ghostpacer.frame.Avatar")
	proto.RegisterType((*Menu)(nil), "ghostpacer.frame.Menu")
	proto.RegisterType((*Banner)(nil), "ghostpacer.frame.Banner")
	proto.RegisterType((*Legend)(nil), "ghostpacer.frame.Legend")
	proto.RegisterType((*Frame)(nil), "ghostpacer.frame.Frame")
}

func init() { proto.RegisterFile("frame1.proto", fileDescriptor_ac775132823699ce) }

var fileDescriptor_ac775132823699ce = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0xb5, 0xb4, 0x94, 0xee, 0x5d, 0x24, 0xcd, 0xc4, 0x98, 0xc6, 0x07, 0xc5, 0x3e, 0x18, 0xb2,
	0x89, 0x65, 0xb7, 0xbc, 0xf8, 0xa2, 0x86, 0x35, 0x68, 0xdc, 0xec, 0x2a, 0x99, 0xe0, 0x3e, 0xf8,
	0x36, 0x94, 0x11, 0x9a, 0xd0, 0x19, 0xd2, 0x0e, 0xbb, 0xb0, 0x0f, 0x7e, 0x80, 0xbf, 0xe3, 0x2f,
	0xf8, 0x61, 0x66, 0x66, 0x5a, 0x60, 0x61, 0xb7, 0x4b, 0xf4, 0x89, 0xde, 0x3b, 0xe7, 0x1c, 0xee,
	0xb9, 0x9d, 0x53, 0xa8, 0xff, 0x48, 0x49, 0x42, 0x4f, 0x82, 0x59, 0xca, 0x05, 0x47, 0xee, 0x78,
	0xc2, 0x33, 0x31, 0x23, 0x11, 0x4d, 0x03, 0x75, 0xe0, 0x1f, 0x83, 0x75, 0x49, 0xa3, 0x0e, 0xaa,
	0x83, 0xb1, 0xf0, 0x8c, 0xa6, 0xd1, 0x32, 0xb0, 0xb1, 0x90, 0xd5, 0xd2, 0xab, 0xe8, 0x6a, 0x29,
	0xab, 0x1b, 0xcf, 0xd4, 0xd5, 0x8d, 0xff, 0xcb, 0x00, 0xeb, 0x82, 0x88, 0x0e, 0x3a, 0x02, 0x2b,
	0xe5, 0xd7, 0x27, 0x8a, 0x75, 0x18, 0x3e, 0x0d, 0xb6, 0xb5, 0x03, 0x29, 0x8c, 0x15, 0x26, 0xc7,
	0x86, 0x4a, 0xb3, 0x1c, 0x1b, 0xe6, 0xd8, 0x8e, 0xfa, 0xc7, 0x72, 0x6c, 0xc7, 0xff, 0x63, 0x82,
	0xdd, 0xbd, 0x22, 0x82, 0xa4, 0xe8, 0x1d, 0x34, 0x88, 0x7a, 0xea, 0xf3, 0x2c, 0x16, 0x31, 0x67,
	0x0f, 0x0c, 0xb6, 0x85, 0x46, 0x6f, 0xe0, 0x50, 0x77, 0x06, 0xfc, 0x92, 0x46, 0x9e, 0x5d, 0x4a,
	0xde, 0x84, 0xae, 0x99, 0xdf, 0x66, 0x92, 0x59, 0xdb, 0x87, 0xa9, 0xa0, 0xe8, 0x15, 0x34, 0x08,
	0x8b, 0x13, 0x22, 0x07, 0xe8, 0x4f, 0x48, 0x46, 0xf3, 0x35, 0x6f, 0x75, 0xa5, 0xb7, 0x88, 0x24,
	0x34, 0x25, 0x2b, 0x6f, 0x56, 0xb9, 0xb7, 0xdb, 0x68, 0x39, 0xa1, 0xee, 0x68, 0x6f, 0x4e, 0xf9,
	0x84, 0x1b, 0xd0, 0x35, 0x53, 0x7b, 0x3b, 0xd8, 0x87, 0xa9, 0xbd, 0x3d, 0x07, 0x48, 0xf8, 0x88,
	0x4e, 0x3f, 0xb3, 0x11, 0x5d, 0x78, 0xd0, 0x34, 0x5a, 0x8f, 0xf1, 0x46, 0xe7, 0xcc, 0x72, 0x2a,
	0xae, 0x79, 0x66, 0x39, 0x55, 0xd7, 0xf6, 0xcf, 0xc1, 0xba, 0xa0, 0x6c, 0x8e, 0x3c, 0xa8, 0x51,
	0x26, 0xd2, 0x98, 0x66, 0x9e, 0xd1, 0x34, 0x5b, 0x07, 0xb8, 0x28, 0xd1, 0x11, 0xb8, 0x24, 0x12,
	0xf1, 0x15, 0xed, 0x31, 0x91, 0x2e, 0xb5, 0x66, 0x45, 0x69, 0xee, 0xf4, 0xfd, 0x9f, 0x60, 0x9f,
	0x12, 0xc6, 0x68, 0x8a, 0x9e, 0x40, 0x75, 0x1a, 0xb3, 0x95, 0x9a, 0x2e, 0xd0, 0x5b, 0x70, 0x66,
	0xc5, 0x1e, 0xa5, 0x46, 0x23, 0x7c, 0xb9, 0x6b, 0x48, 0x2b, 0x04, 0xc5, 0x0a, 0xf1, 0x8a, 0xe2,
	0xbf, 0x00, 0x67, 0xb5, 0xd8, 0x1a, 0x98, 0x83, 0xaf, 0x7d, 0xf7, 0x11, 0x02, 0xb0, 0x3f, 0xf4,
	0xbe, 0x0c, 0x7a, 0xd8, 0x35, 0xfc, 0x09, 0xd8, 0xe7, 0x74, 0x4c, 0xd9, 0x08, 0x3d, 0x03, 0x67,
	0x3e, 0xeb, 0xaa, 0xf9, 0xd4, 0x6d, 0x74, 0xf0, 0xaa, 0x46, 0x3e, 0xd4, 0x33, 0x3a, 0xa5, 0x91,
	0xc8, 0xcf, 0x2b, 0xea, 0xfc, 0x56, 0x4f, 0xee, 0x70, 0xc4, 0xaf, 0x59, 0x8e, 0x30, 0x15, 0x62,
	0xa3, 0xe3, 0xff, 0x36, 0xa1, 0xfa, 0x51, 0x8e, 0x8b, 0x42, 0xa8, 0xe9, 0x8b, 0x55, 0xe4, 0xd1,
	0xdb, 0xb5, 0xa4, 0x83, 0x82, 0x0b, 0xe0, 0x9a, 0x53, 0xe4, 0xf2, 0x41, 0x4e, 0x88, 0x8e, 0xc1,
	0x9e, 0x2a, 0x6f, 0x79, 0x3c, 0xef, 0xa0, 0x68, 0xef, 0x38, 0xc7, 0xc9, 0x38, 0x27, 0x94, 0xcd,
	0xef, 0xbf, 0xb1, 0xf2, 0xcd, 0x63, 0x85, 0x91, 0xea, 0x43, 0xb5, 0x77, 0xaf, 0x7a, 0x9f, 0xba,
	0x7e, 0x2f, 0x38, 0xc7, 0xdd, 0x91, 0x0c, 0xfb, 0x7f, 0x92, 0x51, 0xfb, 0xe7, 0x64, 0x38, 0x7b,
	0x27, 0xe3, 0xb4, 0xfb, 0xfd, 0xfd, 0x38, 0x16, 0x93, 0xf9, 0x30, 0x88, 0x78, 0xd2, 0xfe, 0x24,
	0x09, 0xaf, 0xfb, 0x92, 0xd1, 0x56, 0x5f, 0xe9, 0x88, 0x4f, 0xb3, 0xf6, 0x5a, 0xa6, 0xad, 0x64,
	0xda, 0x63, 0xae, 0x1f, 0x14, 0x64, 0x68, 0xab, 0x9f, 0xce, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x83, 0xaf, 0x35, 0xdf, 0x05, 0x00, 0x00,
}
