# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runup1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='runup1.proto',
  package='ghostpacer.run',
  syntax='proto3',
  serialized_options=_b('Z;github.com/Ghost-Pacer/protocols/ghostpacer/run/go/runproto'),
  serialized_pb=_b('\n\x0crunup1.proto\x12\x0eghostpacer.run\"0\n\nTimedPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x03 \x01(\x02\"\xc6\x01\n\x0bUploadedRun\x12\x11\n\tstartTime\x18\x02 \x01(\x02\x12\x10\n\x08startLat\x18\x03 \x01(\x02\x12\x10\n\x08startLon\x18\x04 \x01(\x02\x12/\n\x0btimedPoints\x18\r \x03(\x0b\x32\x1a.ghostpacer.run.TimedPoint\x12\x13\n\x0bsetRunSplit\x18\x0b \x01(\x02\x12\x10\n\x08userDist\x18\x0c \x01(\x02J\x04\x08\x01\x10\x02J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0b\x42=Z;github.com/Ghost-Pacer/protocols/ghostpacer/run/go/runprotob\x06proto3')
)




_TIMEDPOINT = _descriptor.Descriptor(
  name='TimedPoint',
  full_name='ghostpacer.run.TimedPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ghostpacer.run.TimedPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ghostpacer.run.TimedPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ghostpacer.run.TimedPoint.time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=80,
)


_UPLOADEDRUN = _descriptor.Descriptor(
  name='UploadedRun',
  full_name='ghostpacer.run.UploadedRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTime', full_name='ghostpacer.run.UploadedRun.startTime', index=0,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startLat', full_name='ghostpacer.run.UploadedRun.startLat', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startLon', full_name='ghostpacer.run.UploadedRun.startLon', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timedPoints', full_name='ghostpacer.run.UploadedRun.timedPoints', index=3,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setRunSplit', full_name='ghostpacer.run.UploadedRun.setRunSplit', index=4,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userDist', full_name='ghostpacer.run.UploadedRun.userDist', index=5,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=281,
)

_UPLOADEDRUN.fields_by_name['timedPoints'].message_type = _TIMEDPOINT
DESCRIPTOR.message_types_by_name['TimedPoint'] = _TIMEDPOINT
DESCRIPTOR.message_types_by_name['UploadedRun'] = _UPLOADEDRUN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimedPoint = _reflection.GeneratedProtocolMessageType('TimedPoint', (_message.Message,), dict(
  DESCRIPTOR = _TIMEDPOINT,
  __module__ = 'runup1_pb2'
  # @@protoc_insertion_point(class_scope:ghostpacer.run.TimedPoint)
  ))
_sym_db.RegisterMessage(TimedPoint)

UploadedRun = _reflection.GeneratedProtocolMessageType('UploadedRun', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADEDRUN,
  __module__ = 'runup1_pb2'
  # @@protoc_insertion_point(class_scope:ghostpacer.run.UploadedRun)
  ))
_sym_db.RegisterMessage(UploadedRun)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
