# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track_start_point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='track_start_point.proto',
  package='ghostpacer.run',
  syntax='proto3',
  serialized_options=_b('Z;github.com/Ghost-Pacer/protocols/ghostpacer/run/go/runproto'),
  serialized_pb=_b('\n\x17track_start_point.proto\x12\x0eghostpacer.run*;\n\x0fTrackStartPoint\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02P1\x10\x01\x12\x06\n\x02P2\x10\x02\x12\x06\n\x02P3\x10\x03\x12\x06\n\x02P4\x10\x04\x42=Z;github.com/Ghost-Pacer/protocols/ghostpacer/run/go/runprotob\x06proto3')
)

_TRACKSTARTPOINT = _descriptor.EnumDescriptor(
  name='TrackStartPoint',
  full_name='ghostpacer.run.TrackStartPoint',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P4', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=43,
  serialized_end=102,
)
_sym_db.RegisterEnumDescriptor(_TRACKSTARTPOINT)

TrackStartPoint = enum_type_wrapper.EnumTypeWrapper(_TRACKSTARTPOINT)
NONE = 0
P1 = 1
P2 = 2
P3 = 3
P4 = 4


DESCRIPTOR.enum_types_by_name['TrackStartPoint'] = _TRACKSTARTPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
