// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.6.1
// source: runup1.proto

package runproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimedPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Time float32 `protobuf:"fixed32,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TimedPoint) Reset() {
	*x = TimedPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runup1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimedPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimedPoint) ProtoMessage() {}

func (x *TimedPoint) ProtoReflect() protoreflect.Message {
	mi := &file_runup1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimedPoint.ProtoReflect.Descriptor instead.
func (*TimedPoint) Descriptor() ([]byte, []int) {
	return file_runup1_proto_rawDescGZIP(), []int{0}
}

func (x *TimedPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TimedPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TimedPoint) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type UploadedRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime   float32       `protobuf:"fixed32,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StartLat    float32       `protobuf:"fixed32,3,opt,name=startLat,proto3" json:"startLat,omitempty"`
	StartLon    float32       `protobuf:"fixed32,4,opt,name=startLon,proto3" json:"startLon,omitempty"`
	TimedPoints []*TimedPoint `protobuf:"bytes,13,rep,name=timedPoints,proto3" json:"timedPoints,omitempty"`
	SetRunSplit float32       `protobuf:"fixed32,11,opt,name=setRunSplit,proto3" json:"setRunSplit,omitempty"`
	UserDist    float32       `protobuf:"fixed32,12,opt,name=userDist,proto3" json:"userDist,omitempty"`
}

func (x *UploadedRun) Reset() {
	*x = UploadedRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runup1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadedRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedRun) ProtoMessage() {}

func (x *UploadedRun) ProtoReflect() protoreflect.Message {
	mi := &file_runup1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedRun.ProtoReflect.Descriptor instead.
func (*UploadedRun) Descriptor() ([]byte, []int) {
	return file_runup1_proto_rawDescGZIP(), []int{1}
}

func (x *UploadedRun) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UploadedRun) GetStartLat() float32 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *UploadedRun) GetStartLon() float32 {
	if x != nil {
		return x.StartLon
	}
	return 0
}

func (x *UploadedRun) GetTimedPoints() []*TimedPoint {
	if x != nil {
		return x.TimedPoints
	}
	return nil
}

func (x *UploadedRun) GetSetRunSplit() float32 {
	if x != nil {
		return x.SetRunSplit
	}
	return 0
}

func (x *UploadedRun) GetUserDist() float32 {
	if x != nil {
		return x.UserDist
	}
	return 0
}

var File_runup1_proto protoreflect.FileDescriptor

var file_runup1_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x75, 0x6e, 0x75, 0x70, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x67, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x72, 0x75, 0x6e, 0x22, 0x3c,
	0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x89, 0x02, 0x0a,
	0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x52, 0x75, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x4c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x4c, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c,
	0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x70,
	0x61, 0x63, 0x65, 0x72, 0x2e, 0x72, 0x75, 0x6e, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74, 0x4a, 0x04,
	0x08, 0x01, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x07,
	0x4a, 0x04, 0x08, 0x07, 0x10, 0x08, 0x4a, 0x04, 0x08, 0x08, 0x10, 0x09, 0x4a, 0x04, 0x08, 0x09,
	0x10, 0x0a, 0x4a, 0x04, 0x08, 0x0a, 0x10, 0x0b, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x50, 0x61, 0x63,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x70, 0x61, 0x63, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x72,
	0x75, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runup1_proto_rawDescOnce sync.Once
	file_runup1_proto_rawDescData = file_runup1_proto_rawDesc
)

func file_runup1_proto_rawDescGZIP() []byte {
	file_runup1_proto_rawDescOnce.Do(func() {
		file_runup1_proto_rawDescData = protoimpl.X.CompressGZIP(file_runup1_proto_rawDescData)
	})
	return file_runup1_proto_rawDescData
}

var file_runup1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runup1_proto_goTypes = []interface{}{
	(*TimedPoint)(nil),  // 0: ghostpacer.run.TimedPoint
	(*UploadedRun)(nil), // 1: ghostpacer.run.UploadedRun
}
var file_runup1_proto_depIdxs = []int32{
	0, // 0: ghostpacer.run.UploadedRun.timedPoints:type_name -> ghostpacer.run.TimedPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_runup1_proto_init() }
func file_runup1_proto_init() {
	if File_runup1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runup1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimedPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runup1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadedRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runup1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runup1_proto_goTypes,
		DependencyIndexes: file_runup1_proto_depIdxs,
		MessageInfos:      file_runup1_proto_msgTypes,
	}.Build()
	File_runup1_proto = out.File
	file_runup1_proto_rawDesc = nil
	file_runup1_proto_goTypes = nil
	file_runup1_proto_depIdxs = nil
}
